### ISSUE TITLE
MIT License?

### ISSUE THREAD

**Issue by RussellHaley** [laziu/ppp-test#1]
Hello,

Thank you!!! Please MIT License? 🙏

I will re-use for embedded implementation on MCUs?

신의 축복

**Comment by laziu** [comment]
> Hello,
> 
> Thank you!!! Please MIT License? 🙏
> 
> I will re-use for embedded implementation on MCUs?
> 
> 신의 축복

Yes, it's on MIT License :)
But I recommend you to use better implementation since I made this project for sophomore assignments,
and it hasn't been tested to use in production.

**Comment by RussellHaley** [comment]
Ah, excellent. I looked at the code and didn't see a license file. 

Thank you, I did recognize that the code was from an assignment. I need a reference implementation because I will attempt to port it to an RTOS called TNeo. This code greatly shortens my path because it only uses a handful of posix commands.

Thank you!
